//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock_Holmes_Text_Adventure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock_Holmes_Text_Adventure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28355_old_paper_background_4500x3090_retina {
            get {
                object obj = ResourceManager.GetObject("28355-old-paper-background-4500x3090-retina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b2cc82ed59bff1f6113a728e4b21473e {
            get {
                object obj = ResourceManager.GetObject("b2cc82ed59bff1f6113a728e4b21473e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Brain {
            get {
                object obj = ResourceManager.GetObject("Brain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanishing from Hyde Park.
        /// </summary>
        internal static string CaseTitle {
            get {
                return ResourceManager.GetString("CaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d014a5d5fcedd3cb4fe39aa1b026b42e {
            get {
                object obj = ResourceManager.GetObject("d014a5d5fcedd3cb4fe39aa1b026b42e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ellis {
            get {
                object obj = ResourceManager.GetObject("Ellis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We knock at 221B Baker Street, and to our greatest surprise, Holmes himself answers the door. “Ah, you arrive at the best possible moment: you are expected in the kitchen. I&apos;ll be fair play, Wiggins, I&apos;ll let you get a head start to solve this case which, on the whole, is rather banal…&quot; 
        ///We hear Watson&apos;s wrathful voice coming from the kitchen: “None of this is a game, you can&apos;t leave like this!&quot; 
        ///“Watch me!&quot; replies a jolly Holmes, going down the few stairs separating him from the street, leaving us alone [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lomax {
            get {
                object obj = ResourceManager.GetObject("Lomax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME;ADDRESS
        ///A. A. Goldsmith;93NW
        ///A. B. Cahn &amp; Co;20E
        ///A. B. Muirhead;41EC
        ///A. Marx &amp; Co;36SE
        ///A. W. Faber;29EC
        ///Aaron, Andrew;1E
        ///Abbott, Ruth;38NW
        ///Abbott, Walter;38NW
        ///Aberdeen Navigation Co;26EC
        ///Abernathy, Elmer;86SE
        ///Abernathy, Graham;5E
        ///Abrahams, O.L.D.;75SE
        ///Abramoff, Nicoli;20E
        ///Ackerman, L;5SE
        ///Acorn, Philbert;30E
        ///Acree, Joseph;47EC
        ///Adair, Hilda;59NW
        ///Adair, M;59NW
        ///Adair, Ronald;59NW
        ///Adam, Sir Henry;1SW
        ///Adams, Harmon;43NW
        ///Adelaide-Southampton Line;15E
        ///Admiralty, The;10SW
        ///Adrian, Adrian; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string London_Directory {
            get {
                return ResourceManager.GetString("London_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME;ADDRESS
        ///AUCTION HOUSES;
        ///Armitage’s Gallery;21NW
        ///Bonham’s;12NW
        ///Christie’s;87SW
        ///Gartling’s Art Salon;75WC
        ///Sotheby’s;78NW
        ///BANKS;
        ///Bank of England;23EC
        ///Capital &amp; Counties;75NW
        ///City &amp; Suburban;72EC
        ///Continental Bank;68WC
        ///Cox &amp; Co;22WC
        ///Credit Lyonnais;60SW
        ///Drummond’s Bank;26WC
        ///Holder &amp; Stevenson;69EC
        ///Sylvester’s;84EC
        ///Worthingdon Bank;67NW
        ///BARRISTERS;
        ///Attard, Charles;34EC
        ///Bakersfield, Woodward;21NW
        ///Faversham, F.V;32WC
        ///Hall, Edward;36EC
        ///Krantz, Herbert;72WC
        ///Mason, Cecil;92EC
        ///Nast, Flaviu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string London_Directory_Catagories {
            get {
                return ResourceManager.GetString("London_Directory_Catagories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MapZoomed {
            get {
                object obj = ResourceManager.GetObject("MapZoomed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meeks {
            get {
                object obj = ResourceManager.GetObject("Meeks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Murray {
            get {
                object obj = ResourceManager.GetObject("Murray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We all gather in Mrs Hudsonâ€™s living room. On the coffee table, there is a vase with a bunch of violets. In a corner of the room, a dog is eating meat from a bowl, paying no attention to us. Holmes starts without preamble:â€œAn easy case to solve. A letter, with no ransom demand, A very considerate culprit, or anxious not to draw attention. A discreet abduction during the usual walk of our client: this most probably points to a close acquaintance. The nephew, reporter at the Times? Given the article on th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Outro {
            get {
                return ResourceManager.GetString("Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pike {
            get {
                object obj = ResourceManager.GetObject("Pike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Porky {
            get {
                object obj = ResourceManager.GetObject("Porky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SherlockHolmes {
            get {
                object obj = ResourceManager.GetObject("SherlockHolmes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhabitant;Location;Information
        ///Sherlock Holmes (Consulting Detective);42NW;“Come now Wiggins, you can solve this case on your own&quot;
        ///Lomax (Librarian);5SW;&quot;Sorry Wiggins I don&apos;t think I can be of much help to you&quot;
        ///Central Carriage Depot;5WC;&quot;Sorry Wiggins I don&apos;t think I can be of much help to you&quot;
        ///Sir Jasper Meeks (Medical Examiner);38EC;&quot;Sorry Wiggins I don&apos;t think I can be of much help to you&quot;
        ///Langdale Pike (Social Columnist);2SW;&quot;Pike receives us in the visitors sitting-room: “Oppenheimer was alread [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SherlockLocations {
            get {
                return ResourceManager.GetString("SherlockLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question;Possible Answers;Answer
        ///1. Who abducted Charly?;Yvonne Nance?The nightwatch?Grosvenor Investments?Howard Parker?Stuart Oppenheimer?Oscar Teevan?Patrick Hennessy;Howard Parker
        ///2. Why?;To discreetly enter the Grosvenor Investments?Money Extortion from Mrs Nance?To be eaten?To replace his lost pet;To discreetly enter the Grosvenor Investments
        ///3. Where is Charly?;Baker Meat?Cannon?Chinese Wonders?At Howard Parker&apos;s?At Stuart Oppenheimer&apos;s?At Patrick Henessy&apos;s?At Grosvenor Investment&apos;s;At Howard Park [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SherlockQuestions {
            get {
                return ResourceManager.GetString("SherlockQuestions", resourceCulture);
            }
        }
    }
}
